version: '3.8'

services:
  db:
    image: postgres    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data: